CREATE DATABASE CLOUD;
USE CLOUD;

CREATE TABLE `CLOUD_USER` (
    `USER_ID` bigint(11) NOT NULL AUTO_INCREMENT,
    `USER_NAME` bigint(11) NOT NULL,
    `USER_NICK_NAME` bigint(11) NOT NULL,
    `PASSWORD` bigint(11) NOT NULL,
    `LAST_LOGIN_TIME` timestamp NULL DEFAULT NULL,
    PRIMARY KEY (`USER_ID`) USING BTREE,
    UNIQUE KEY `USER_NAME` (`USER_NAME`),
    UNIQUE KEY `USER_NICK_NAME` (`USER_NICK_NAME`),
    UNIQUE KEY `UK_USERS_NAME` (`USER_NAME`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
